# Generated by Django 5.1.1 on 2024-11-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontodecoleta',
            name='descricao',
            field=models.CharField(default='Default Description', max_length=255),
        ),
        migrations.AddField(
            model_name='pontodecoleta',
            name='local',
            field=models.CharField(default=1, max_length=200, verbose_name='Endereço do ponto de coleta'),
            preserve_default=False,
        ),
    ]
