# Generated by Django 5.1.1 on 2024-11-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pontodecoleta_descricao_pontodecoleta_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontodecoleta',
            name='coordenadaX',
            field=models.CharField(default='Default X', max_length=255, verbose_name='coordenada X no mapa'),
        ),
        migrations.AddField(
            model_name='pontodecoleta',
            name='coordenadaY',
            field=models.CharField(default='Default Y', max_length=255, verbose_name='coordenada Y no mapa'),
        ),
    ]
