# Generated by Django 5.1.1 on 2024-11-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_pontodecoleta_coordenadax_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Empresa')),
                ('cnpj', models.CharField(max_length=100, verbose_name='CNPJ')),
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Email')),
                ('senha', models.CharField(max_length=100, verbose_name='Senha')),
            ],
        ),
    ]
