# Generated by Django 5.1.1 on 2024-11-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='descricao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Descricão da empresa'),
        ),
        migrations.AddField(
            model_name='user',
            name='servicos',
            field=models.CharField(blank=True, max_length=100, verbose_name='serviços prestados'),
        ),
    ]
