# Generated by Django 5.1.1 on 2024-11-24 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_descricao_user_servicos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
        migrations.AddField(
            model_name='pontodecoleta',
            name='cnpj',
            field=models.CharField(default='Default Description', max_length=255),
        ),
    ]
