# Generated by Django 5.1.1 on 2024-12-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_user_pontodecoleta_cnpj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontodecoleta',
            name='coordenadaX',
        ),
        migrations.RemoveField(
            model_name='pontodecoleta',
            name='coordenadaY',
        ),
        migrations.AlterField(
            model_name='pontodecoleta',
            name='cnpj',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pontodecoleta',
            name='descricao',
            field=models.CharField(default='', max_length=255),
        ),
    ]
